apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ai-k8s-selfhost
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: ai-k8s-selfhost-container
        image: saars/ai_k8s_selfhost:latest

